Repository Yoast/wpseo-news, pull requests merged in 2018-05, with the labels that each got.

#407 Exclude artifact folder from POT file generation
  grunt/config/makepot.js
Labels: in progress

#401 WPSEO_News_Sitemap_Images::parse_image_source(): fix handling of protocol relative URLs
  classes/class-sitemap-images.php
  tests/framework/class-wpseo-news-unit-test-case.php
  tests/test-class-sitemap-images.php
Labels: acceptance, bug, in progress

#411 Jdv/remove stuff
  classes/class-admin-page.php
  classes/class-editors-pick-request.php
  classes/class-head.php
  classes/class-meta-box.php
  classes/class-sitemap-editors-pick.php
  classes/class-wpseo-news.php
  tests/test-class-sitemap-editors-pick.php
Labels: acceptance

#405 Redid the tests to make them compatible with PHP 5.2
  tests/test-class-sitemap.php
Labels: acceptance

#404 CS: Clean up after latest merges
  tests/test-class-sitemap.php
Labels: development, in progress
