Repository Yoast/wpseo-news, pull requests merged in 2018-03, with the labels that each got.

#376 CS/XSS: remove need to escape output [5]
  classes/class-admin-page.php
Labels: code-review

#361 CS/QA: consistently use `WPSEO_NEWS_FILE` constant
  classes/class-wpseo-news.php
  wpseo-news.php
Labels: code-review

#371 Update `Depends` header
  README.md
  wpseo-news.php
Labels: yoast cs

#375 CS/XSS: always escape output [4]
  classes/class-admin-page.php
Labels: code-review

#354 CS/QA: remove superfluous fall-back function
  classes/class-meta-box.php
Labels: yoast cs

#374 CS/XSS: always escape output [3]
  classes/class-meta-box.php
Labels: yoast cs

#373 CS/XSS: always escape output [2]
  classes/class-wpseo-news.php
Labels: yoast cs

#384 CS: clean up after latest merges
  classes/class-wpseo-news.php
Labels: yoast cs

#386 Security: add Roave/SecurityAdvisories dependency
  composer.json
  composer.lock
Labels: needs-code-review

#372 CS/XSS: always escape output [1]
  classes/class-head.php
Labels: yoast cs

#360 CS/SQL: refactor query using ` IN ()`
  classes/class-sitemap.php
Labels: yoast cs

#389 Remove news keywords everywhere
  assets/post-edit.js
  assets/post-edit.min.js
  assets/xml-news-sitemap.xsl
  classes/class-admin-page.php
  classes/class-head.php
  classes/class-meta-box.php
  classes/class-meta-keywords.php
  classes/class-sitemap-item.php
  classes/class-upgrade-manager.php
  classes/class-wpseo-news.php
  languages/wordpress-seo-news-en_NZ.mo
  languages/wordpress-seo-news.pot
  tests/test-class-sitemap.php
Labels: needs-code-review

#388 Documentation: various fixes
  classes/class-admin-page.php
  classes/class-beacon-setting.php
  classes/class-editors-pick-request.php
  classes/class-head.php
  classes/class-javascript-strings.php
  classes/class-meta-box.php
  classes/class-news-wrappers.php
  classes/class-product.php
  classes/class-sitemap-editors-pick.php
  classes/class-sitemap-images.php
  classes/class-sitemap-item.php
  classes/class-sitemap-timezone.php
  classes/class-sitemap.php
  classes/class-upgrade-manager.php
  classes/class-wpseo-news.php
  tests/assets/wpseo-news-double.php
  tests/bootstrap.php
  tests/framework/class-wpseo-news-unit-test-case.php
  tests/test-class-admin-page.php
  tests/test-class-sitemap-editors-pick.php
  tests/test-class-sitemap.php
  tests/test-class-wpseo-news.php
  wpseo-news.php
Labels: needs-acceptance

#390 Clean up: Remove outdated comment/merge artifact
  tests/test-class-sitemap.php
Labels: in progress, yoast cs
