Repository Yoast/wpseo-news, pull requests merged in 2019-10, with the labels that each got.

#528 CS: clean up after merges
  classes/admin-page.php
  classes/excludable-taxonomies.php
  classes/meta-box.php
  classes/wpseo-news.php
  integration-tests/meta-box-test.php
  integration-tests/schema-test.php
  tests/TestCase.php
Labels: yoast cs/qa

#541 Bug fix: use the correct function
  tests/bootstrap.php
Labels: changelog: non-user-facing, yoast cs/qa

#542 PHPCompatibility fix: pass encoding to htmlspecialchars() et al functions
  classes/sitemap-images.php
  classes/sitemap-item.php
  classes/sitemap.php
  integration-tests/sitemap-test.php
Labels: yoast cs/qa

#529 QA: use gmdate() instead of date()
  integration-tests/sitemap-item-test.php
  integration-tests/sitemap-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#544 Travis: minor clean up
  .travis.yml
Labels: yoast cs/qa

#546 Rename new testcase file
  tests/testcase.php
Labels: yoast cs/qa

#547 CS/QA: improve output escaping
  classes/admin-page.php
Labels: yoast cs/qa

#549 Set tested up to to 5.3, minimum wp to 5.2 and PHP to 5.6.20
  README.md
Labels: changelog: other

#550 Tidy up PHPUnit config files
  phpunit-integration.xml.dist
  phpunit.xml.dist
Labels: changelog: non-user-facing, yoast cs/qa

#551 PHPUnit bootstrap: friendly error message
  tests/bootstrap.php
Labels: changelog: non-user-facing, yoast cs/qa

#552 PHPUnit: make (new) unit tests compatible with higher PHPUnit versions
  tests/testcase.php
Labels: changelog: non-user-facing, yoast cs/qa

#556 Tests: fix path to WP native bootstrap
  integration-tests/bootstrap.php
Labels: changelog: non-user-facing, yoast cs/qa

#554 Schema: fix failing test
  integration-tests/schema-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#555 Tests: mark two tests for skipping on low PHP versions
  integration-tests/sitemap-item-test.php
  integration-tests/sitemap-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#557 Tests: fix test double classes not being found
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa
