Repository Yoast/wpseo-news, pull requests merged in 2019-12, with the labels that each got.

#580 CS: minor clean up after merges
  integration-tests/sitemap-item-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#578 Add missing multisite checks for the actions
  classes/sitemap.php
Labels: changelog: bugfix

#577 Implement date helper
  classes/admin-page.php
  classes/sitemap-item.php
  classes/sitemap-timezone.php
  classes/sitemap.php
  classes/upgrade-manager.php
  integration-tests/sitemap-item-test.php
  integration-tests/sitemap-test.php
Labels: changelog: non-user-facing

#581 Bump plugin-grunt-tasks
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#579 Composer: update BrainMonkey dependency
  composer.json
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#583 CS: minor whitespace fix
  classes/sitemap.php
Labels: changelog: non-user-facing, yoast cs/qa

#587 CS: don't use Yoda conditions
  classes/sitemap-images.php
  classes/wpseo-news.php
  integration-tests/bootstrap.php
Labels: changelog: non-user-facing, yoast cs/qa

#584 Bugfix: use the magic constant
  classes/sitemap-timezone.php
Labels: changelog: non-user-facing, yoast cs/qa

#586 QA: sanitize use of a superglobal
  classes/meta-box.php
Labels: changelog: non-user-facing, yoast cs/qa
