Repository Yoast/wpseo-news, pull requests merged in 2019-11, with the labels that each got.

#553 Travis: fix broken script
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa

#560 Stop explicit support for PHP < 5.6 / WP < 5.2
  .travis.yml
  composer.json
  composer.lock
  integration-tests/bootstrap.php
  wpseo-news.php
Labels: changelog: non-user-facing, yoast cs/qa

#562 Remove the usage of the seo title
  classes/sitemap-item.php
  integration-tests/sitemap-item-test.php
  integration-tests/sitemap-test.php
Labels: changelog: bugfix, has patch, type: development

#573 Use date helper
  classes/schema.php
Labels: changelog: non-user-facing

#576 Renamed the class we have to use
  classes/schema.php
Labels: changelog: non-user-facing

#569 Travis: don't allow builds against PHP 7.4 to fail
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa
