Repository Yoast/wpseo-news, pull requests merged in 2019-03, with the labels that each got.

#454 Removal of deprecated method
  classes/class-wpseo-news.php
Labels: code-review, has patch

#479 CodeCoverage: ignore deprecated method(s)
  wpseo-news.php
Labels: yoast cs/qa

#478 Documentation: minor fixes
  classes/class-sitemap-item.php
  tests/assets/wpseo-news-double.php
  tests/test-class-admin-page.php
  tests/test-class-sitemap.php
Labels: yoast cs/qa

#477 CS: Rename non-snakecase variable
  tests/test-class-sitemap-item.php
Labels: yoast cs/qa

#476 CS/QA: use `self` when referencing a (static) class member from within the same class
  classes/class-sitemap.php
Labels: yoast cs/qa

#474 CS: Each parameter should start on a new line in multi-line function calls
  classes/class-wpseo-news.php
  tests/test-class-sitemap.php
Labels: yoast cs/qa

#473 CS: PHP keywords should be lowercase
  tests/assets/wpseo-news-sitemap-item-double.php
Labels: yoast cs/qa

#472 CS: fix unnecessary usage of double quotes
  tests/test-class-sitemap-item.php
  tests/test-class-sitemap.php
Labels: yoast cs/qa

#475 CS: Move multi-line parameters out of function calls
  classes/class-wpseo-news.php
  tests/test-class-sitemap-item.php
  tests/test-class-sitemap.php
Labels: yoast cs/qa

#471 CS: various minor whitespace issues
  classes/class-meta-box.php
  classes/class-sitemap-timezone.php
  classes/class-wpseo-news.php
  tests/test-class-admin-page.php
  tests/test-class-sitemap-item.php
  tests/test-class-sitemap.php
Labels: yoast cs/qa

#469 Travis: test against current WP versions
  .travis.yml
Labels: yoast cs/qa

#466 PHPUnit: Rename the config file
  .gitignore
  .travis.yml
  phpunit.xml.dist
Labels: yoast cs/qa

#467 Travis: test builds against PHP 7.4
  .travis.yml
Labels: yoast cs/qa

#484 Test documentation: fix @covers tags
  tests/test-class-sitemap-images.php
  tests/test-class-wpseo-news.php
Labels: yoast cs/qa

#483 Test documentation: fix missing docs
  tests/test-class-sitemap.php
Labels: yoast cs/qa

#481 CS: Move test double classes to separate directory
  tests/doubles/wpseo-news-double.php
  tests/doubles/wpseo-news-sitemap-item-double.php
Labels: yoast cs/qa

#482 CS/QA: don't use assignments in conditions
  classes/class-sitemap-timezone.php
  classes/class-wpseo-news.php
  tests/framework/class-wpseo-news-unit-test-case.php
Labels: yoast cs/qa

#480 Travis: improve dependency security check
  .travis.yml
  composer.json
  composer.lock
Labels: yoast cs/qa

#442 Fixed Sitemap image URLs to use href instead of guid.
  classes/class-sitemap-images.php
Labels: community-patch
