Repository Yoast/wpseo-news, pull requests merged in 2020-08, with the labels that each got.

#646 Set minimum WP version to 5.4 and tested up to to 5.5
  .travis.yml
  README.md
  integration-tests/wpseo-news-test.php
Labels: changelog: other

#647 Enables tracking on plugin activation.
  wpseo-news.php
Labels: changelog: non-user-facing

#648 P1 113 Page does not output NewsArticle
  classes/schema.php
  integration-tests/schema-test.php
Labels: changelog: bugfix

#649 P1-125 Fix NewsArticle not working when the current article type is None
  classes/schema.php
  integration-tests/schema-test.php
Labels: changelog: non-user-facing

#650 [QAK-2167] Check if WPSEO_Options exists before calling one of its methods
  wpseo-news.php
Labels: changelog: non-user-facing
