Repository Yoast/wpseo-news, pull requests merged in 2020-04, with the labels that each got.

#626 Adapts the presenter interface changed made in Yoast SEO
  classes/googlebot-news-presenter.php
  tests/googlebot-news-presenter-test.php
  tests/news-test.php
Labels: changelog: non-user-facing

#627 Set minimum WP version to 5.3
  classes/wpseo-news.php
  integration-tests/wpseo-news-test.php
Labels: changelog: other

#629 Composer: update YoastCS to v 2.0.2
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#630 QA: add missing import `use` statements for classes
  tests/googlebot-news-presenter-test.php
  tests/news-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#631 QA: remove useless variable
  classes/meta-box.php
Labels: changelog: non-user-facing, yoast cs/qa

#632 Docs: various minor fixes
  classes/meta-box.php
  classes/wpseo-news.php
  tests/googlebot-news-presenter-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#633 Update travis matrix because of new WP version
  .travis.yml
Labels: changelog: non-user-facing

#634 CS: no `use` statements for same namespace
  tests/googlebot-news-presenter-test.php
  tests/news-test.php
  tests/option-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#635 CS: don't use FQN in docblocks
  classes/wpseo-news.php
  integration-tests/admin-page-test.php
  integration-tests/sitemap-images-test.php
  integration-tests/sitemap-test.php
  tests/googlebot-news-presenter-test.php
  tests/option-test.php
Labels: changelog: non-user-facing, yoast cs/qa
