Repository Yoast/wpseo-news, pull requests merged in 2020-01, with the labels that each got.

#591 Integration with the WPSEO Options framework.
  classes/admin-page.php
  classes/excludable-taxonomies.php
  classes/meta-box.php
  classes/option.php
  classes/schema.php
  classes/sitemap-images.php
  classes/sitemap-item.php
  classes/sitemap.php
  classes/upgrade-manager.php
  classes/wpseo-news.php
  integration-tests/schema-test.php
  integration-tests/sitemap-images-test.php
  integration-tests/sitemap-item-test.php
  integration-tests/sitemap-test.php
Labels: changelog: non-user-facing

#589 PHPCS: Update to YoastCS 1.3.0
  .gitignore
  .phpcs.xml.dist
  .travis.yml
  classes/sitemap-images.php
  classes/sitemap-item.php
  classes/sitemap.php
  classes/upgrade-manager.php
  composer.json
  composer.lock
  phpcs.xml
  tests/testcase.php
  wpseo-news.php
Labels: changelog: non-user-facing, yoast cs/qa

#594 Change the hook priority
  classes/wpseo-news.php
Labels: changelog: non-user-facing

#600 Fixes the performance
  classes/admin-page.php
  classes/option.php
  classes/upgrade-manager.php
  classes/wpseo-news.php
  tests/doubles/option-double.php
  tests/news-test.php
  tests/option-test.php
Labels: bug, changelog: bugfix

#602 Fix various CS errors and warnings
  .phpcs.xml.dist
  classes/admin-page.php
  classes/wpseo-news.php
  tests/doubles/option-double.php
  tests/news-test.php
  tests/option-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#603 Travis: use 7.4 not snapshot
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa

#607 CS: clean up after merges
  classes/meta-box.php
  classes/product.php
  tests/testcase.php
Labels: changelog: non-user-facing, yoast cs/qa

#605 Modernize: use `__DIR__` instead of `dirname( __FILE__ )`
  integration-tests/bootstrap.php
  wpseo-news.php
Labels: changelog: non-user-facing, yoast cs/qa

#606 Modernize: use nowdoc instead of heredoc
  integration-tests/admin-page-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#608 Integration tests: bug fix / typo
  integration-tests/admin-page-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#609 QA: remove unused variable
  integration-tests/sitemap-item-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#610 QA: remove useless variables
  classes/sitemap-item.php
  classes/sitemap.php
Labels: changelog: non-user-facing, yoast cs/qa

#611 QA: add missing `use` statements
  tests/doubles/option-double.php
  tests/news-test.php
  tests/option-test.php
  tests/testcase.php
Labels: changelog: non-user-facing, yoast cs/qa

#612 QA: declare static closures as static
  tests/testcase.php
Labels: changelog: non-user-facing, yoast cs/qa

#613 QA: remove redundant variable assignment
  integration-tests/sitemap-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#614 Tests: remove WIP copy/paste code
  tests/news-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#615 QA: use FQN function calls in namespaced files
  tests/testcase.php
Labels: changelog: non-user-facing, yoast cs/qa

#616 Docs: various fixes
  classes/excludable-taxonomies.php
  classes/head.php
  classes/javascript-strings.php
  classes/meta-box.php
  classes/schema.php
  classes/sitemap-images.php
  classes/sitemap-item.php
  classes/sitemap.php
  classes/upgrade-manager.php
  classes/wpseo-news.php
  integration-tests/doubles/sitemap-item-double.php
  integration-tests/doubles/wpseo-news-double.php
  integration-tests/framework/unittestcase.php
  integration-tests/sitemap-item-test.php
  integration-tests/sitemap-test.php
  integration-tests/wpseo-news-test.php
  tests/option-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#604 PHPCS: Update to YoastCS 2.0.0
  .phpcs.xml.dist
  classes/admin-page.php
  classes/excludable-taxonomies.php
  classes/head.php
  classes/javascript-strings.php
  classes/meta-box.php
  classes/option.php
  classes/schema.php
  classes/sitemap-images.php
  classes/sitemap.php
  classes/upgrade-manager.php
  classes/wpseo-news.php
  composer.json
  composer.lock
  integration-tests/bootstrap.php
  integration-tests/framework/unittestcase.php
  integration-tests/meta-box-test.php
  integration-tests/schema-test.php
  integration-tests/sitemap-images-test.php
  integration-tests/sitemap-item-test.php
  integration-tests/sitemap-test.php
  integration-tests/wpseo-news-test.php
  wpseo-news.php
Labels: changelog: other, yoast cs/qa
