Repository Yoast/wpseo-news, pull requests merged in 2021-06, with the labels that each got.

#694 Allow filtering of decision to skip building sitemap item
  classes/sitemap-item.php
Labels: changelog: enhancement, community-patch

#679 Add the ability to filter News Sitemap items for exclusion
  classes/sitemap-item.php
Labels: community-patch

#696 remove duplicate selection of `post_date_gmt`
  classes/sitemap.php
Labels: changelog: bugfix

#697 add Earlier versions to READme.md
  README.md
Labels: changelog: non-user-facing

#698 Set the minimum required WP version to 5.6
  classes/wpseo-news.php
Labels: changelog: other

#699 Add config for Changelog grunt tasks
  .gitignore
  Gruntfile.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/build-qa-changelog.js
  config/grunt/task-config/download-qa-changelog.js
  config/grunt/task-config/update-changelog-with-latest-pr-texts.js
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#691 Adjust sitemap query to improve performance
  classes/sitemap.php
  integration-tests/sitemap-test.php
Labels: changelog: enhancement
