Repository Yoast/wpseo-news, pull requests merged in 2021-11, with the labels that each got.

#721 Move to an Indexables based XML News Sitemap
  assets/xml-news-sitemap.xsl
  classes/admin-page.php
  classes/sitemap-images.php
  classes/sitemap-item.php
  classes/sitemap.php
  classes/upgrade-manager.php
  classes/wpseo-news.php
  integration-tests/doubles/sitemap-item-double.php
  integration-tests/sitemap-images-test.php
  integration-tests/sitemap-item-test.php
  integration-tests/sitemap-test.php
Labels: changelog: enhancement

#722 DUPP-61 Remove code hooking into the deprecated `wpseo_schema_article_post_types` filter
  classes/schema.php
  integration-tests/schema-test.php
Labels: changelog: non-user-facing

#723 DUPP-65 Update minimum required Free version to 17.6
  classes/wpseo-news.php
  integration-tests/wpseo-news-test.php
Labels: changelog: non-user-facing

#724 [DUPP-67] Fix exclude join query
  classes/sitemap.php
Labels: changelog: non-user-facing

#726 DUPP-76 Delay the update of excluded terms options to have all CPTs registered
  classes/upgrade-manager.php
Labels: changelog: non-user-facing

#725 DUPP-73 Remove not indexed post types from sitemap
  classes/admin-page.php
  classes/sitemap.php
Labels: changelog: other, UI change

#727 DUPP-78 Fix bug in query
  classes/sitemap.php
Labels: changelog: non-user-facing
