Repository Yoast/wpseo-news, pull requests merged in 2021-03, with the labels that each got.

#677 Bump minimal required WPSEO version
  classes/wpseo-news.php
  integration-tests/wpseo-news-test.php
Labels: changelog: non-user-facing

#678 P1-301 reactify editor
  .babelrc
  classes/admin-page.php
  classes/integrations/editor-changes-alert.php
  classes/meta-box.php
  classes/sitemap-item.php
  classes/upgrade-manager.php
  classes/wpseo-news.php
  config/webpack/externals.js
  config/webpack/paths.js
  config/webpack/webpack.config.js
  integration-tests/meta-box-test.php
  integration-tests/sitemap-test.php
  js/src/components/Editor.js
  js/src/components/Metabox.js
  js/src/components/Sidebar.js
  js/src/containers/EditorContainer.js
  js/src/helpers/fields/EditorFields.js
  js/src/initializers/initializeEditorPage.js
  js/src/initializers/initializeSettingsPage.js
  js/src/redux/actions/editor.js
  js/src/redux/reducers/editor.js
  js/src/redux/selectors/editor.js
  js/src/yoast-seo-news-editor.js
  js/src/yoast-seo-news-settings.js
  package.json
  yarn.lock
Labels: UI change, changelog: enhancement, innovation

#681 Set tested up to to WP 5.7 and minimum to 5.6
  .travis.yml
  README.md
  integration-tests/wpseo-news-test.php
Labels: changelog: other

#680 P3-362 Move reading of options outside functions called by options cache priming, to avoid loops
  classes/wpseo-news.php
  tests/bootstrap.php
Labels: changelog: bugfix

#684 P1-442 Bump minimal required WPSEO version
  classes/wpseo-news.php
  integration-tests/wpseo-news-test.php
Labels: changelog: non-user-facing

#685 Remove deprecated methods
  classes/meta-box.php
  classes/sitemap-timezone.php
  wpseo-news.php
Labels: changelog: non-user-facing
