Repository Yoast/wpseo-news, pull requests merged in 2021-10, with the labels that each got.

#718 Add Schema Article News subtypes
  classes/schema.php
  integration-tests/schema-test.php
Labels: changelog: enhancement, UI change

#717 Update (fix) test setup
  .travis.yml
  composer.json
  composer.lock
  integration-tests/admin-page-test.php
  integration-tests/schema-test.php
  integration-tests/sitemap-images-test.php
  integration-tests/sitemap-test.php
  phpunit-integration.xml.dist
  phpunit.xml.dist
Labels: yoast cs/qa, changelog: non-user-facing

#719 ignore all files in folder instead of the entire folder
  .gitignore
Labels: changelog: non-user-facing
