Repository Yoast/wpseo-news, pull requests merged in 2021-01, with the labels that each got.

#666 P1-299 remove genre settings
  assets/xml-news-sitemap.xsl
  classes/admin-page.php
  classes/meta-box.php
  classes/option.php
  classes/sitemap-item.php
  classes/upgrade-manager.php
  classes/wpseo-news.php
  yarn.lock
Labels: changelog: other

#667 replace security checker
  .travis.yml
Labels: changelog: non-user-facing, tooling

#668 P1-300 Add notification for changes in News SEO
  classes/wpseo-news.php
Labels: changelog: enhancement

#661 Convert visible URLs to https
  classes/admin-page.php
  wpseo-news.php
Labels: changelog: bugfix, community-patch, has patch
