Repository Yoast/wpseo-news, pull requests merged in 2021-02, with the labels that each got.

#671 Removes the no longer wanted notification
  classes/wpseo-news.php
Labels: changelog: non-user-facing

#672 Improve how we load HelpScout
  classes/wpseo-news.php
Labels: changelog: non-user-facing

#674 P3-361 Update conditional check for get_post_thumbnail_id
  classes/sitemap-images.php
Labels: changelog: non-user-facing

#673 Create webpack tooling
  .babelrc
  .gitignore
  .removeable-files
  Gruntfile.js
  assets/admin-page.js
  classes/wpseo-news.php
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/clean.js
  config/grunt/task-config/copy.js
  config/grunt/task-config/webpack.js
  config/webpack/externals.js
  config/webpack/paths.js
  config/webpack/webpack.config.js
  js/src/initializers/initializeEditorStore.js
  js/src/redux/actions/editor.js
  js/src/redux/actions/index.js
  js/src/redux/reducers/editor.js
  js/src/redux/reducers/index.js
  js/src/redux/selectors/editor.js
  js/src/redux/selectors/index.js
  js/src/yoast-seo-news-plugin.js
  package.json
  yarn.lock
Labels: changelog: non-user-facing, innovation

#675 P1-343 Add JS translations
  .gitignore
  Gruntfile.js
  classes/javascript-strings.php
  classes/wpseo-news.php
  config/grunt/custom-tasks/i18n-clean-json.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/clean.js
  config/grunt/task-config/copy.js
  config/grunt/task-config/glotpress_download.js
  config/grunt/task-config/makepot.js
  config/grunt/task-config/po2json.js
  config/grunt/task-config/shell.js
  config/webpack/externals.js
  js/src/initializers/initializeTranslations.js
  js/src/redux/reducers/editor.js
  js/src/yoast-seo-news-plugin.js
  languages/wordpress-seo-news-ar.mo
  languages/wordpress-seo-news-bg_BG.mo
  languages/wordpress-seo-news-da_DK.mo
  languages/wordpress-seo-news-de_DE.mo
  languages/wordpress-seo-news-el.mo
  languages/wordpress-seo-news-en_AU.mo
  languages/wordpress-seo-news-en_CA.mo
  languages/wordpress-seo-news-en_GB.mo
  languages/wordpress-seo-news-en_NZ.mo
  languages/wordpress-seo-news-es_ES.mo
  languages/wordpress-seo-news-es_MX.mo
  languages/wordpress-seo-news-fa_IR.mo
  languages/wordpress-seo-news-fr_FR.mo
  languages/wordpress-seo-news-he_IL.mo
  languages/wordpress-seo-news-id_ID.mo
  languages/wordpress-seo-news-it_IT.mo
  languages/wordpress-seo-news-ja.mo
  languages/wordpress-seo-news-km.mo
  languages/wordpress-seo-news-lt_LT.mo
  languages/wordpress-seo-news-ms_MY.mo
  languages/wordpress-seo-news-nl_NL.mo
  languages/wordpress-seo-news-pl_PL.mo
  languages/wordpress-seo-news-pt_BR.mo
  languages/wordpress-seo-news-pt_PT.mo
  languages/wordpress-seo-news-ro_RO.mo
  languages/wordpress-seo-news-ru_RU.mo
  languages/wordpress-seo-news-sv_SE.mo
  languages/wordpress-seo-news-tr_TR.mo
  languages/wordpress-seo-news-uk.mo
  languages/wordpress-seo-news-vi.mo
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#676 P1 332 genre removal alert
  classes/admin-page.php
  classes/integrations/settings-genre-removal-alert.php
  classes/wpseo-news.php
  js/src/initializers/initializeSettingsPage.js
  js/src/yoast-seo-news-plugin.js
  yarn.lock
Labels: changelog: enhancement, innovation
