Repository Yoast/wpseo-news, pull requests merged in 2022-11, with the labels that each got.

#765 Composer: update dependencies
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#766 GH Actions: various tweaks
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
  .github/workflows/integrationtest.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
Labels: yoast cs/qa, changelog: non-user-facing

#767 CS: minor fixes
  classes/meta-box.php
  classes/sitemap.php
Labels: yoast cs/qa, changelog: non-user-facing

#768 GH Actions: update cache-busting
  .github/workflows/deploy.yml
Labels: yoast cs/qa, changelog: non-user-facing

#772 Update changelog format (both in file and creation settings)
  README.md
  config/grunt/task-config/update-changelog-to-latest.js
Labels: changelog: non-user-facing

#774 Composer: update test utilities
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#775 Composer: update test utilities (round 2)
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#777 Tests: use import `use` statements for all referenced WP native classes
  tests/googlebot-news-presenter-test.php
  tests/news-test.php
  tests/option-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#776 Remove our yoast i18n composer dependency
  classes/admin-page.php
  composer.json
  composer.lock
  tests/googlebot-news-presenter-test.php
Labels: changelog: enhancement
