Repository Yoast/wpseo-news, pull requests merged in 2022-12, with the labels that each got.

#783 Set minimum WP version to 6.0
  .github/workflows/integrationtest.yml
  README.md
  classes/wpseo-news.php
  integration-tests/wpseo-news-test.php
Labels: changelog: other

#779 Update Bug_report.md
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: changelog: non-user-facing

#782 DUPP-788-news-deprecated-before-12.9
  classes/head.php
  classes/javascript-strings.php
  classes/meta-box.php
  classes/sitemap.php
  classes/wpseo-news.php
Labels: changelog: non-user-facing

#785 GH Actions: various tweaks
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
  .github/workflows/integrationtest.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
Labels: yoast cs/qa, changelog: non-user-facing
