Repository Yoast/wpseo-news, pull requests merged in 2023-01, with the labels that each got.

#786 update plugin-grunt-tasks to 2.4 and update date format in readme.md
  README.md
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#787 Composer: update YoastCS and dependencies
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#788 Fix special characters in publication name
  classes/sitemap.php
Labels: changelog: bugfix
